apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    env: int
    component: ${NAMESPACE}
  annotations:
    meemoo.be/kustomized: "true"
    meemoo.be/project: "${NAMESPACE}"
spec:
  selector:
    matchLabels:
      env: int
  template:
    metadata:
      labels:
        env: int
        component: ${NAMESPACE}
      annotations:
        meemoo.be/kustomized: "true"
        meemoo.be/project: "${NAMESPACE}"
    spec:
      containers:
        - name: ${APP_NAME}
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
