apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    env: qas
    component: ${NAMESPACE}
  annotations:
    meemoo.be/kustomized: "true"
    meemoo.be/project: "${NAMESPACE}"
spec:
  selector:
    matchLabels:
      env: qas
  template:
    metadata:
      labels:
        env: qas
        component: ${NAMESPACE}
      annotations:
        meemoo.be/kustomized: "true"
        meemoo.be/project: "${NAMESPACE}"
    spec:
      containers:
        - name: ${APP_NAME}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "384Mi"
