apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}
  labels:
    env: qas
    component: ${NAMESPACE}
  annotations:
    meemoo.be/kustomized: "true"
    meemoo.be/project: "${NAMESPACE}"
