apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hetarchief-v3

resources:
  - ../../base
  - client-int-externalsecret.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: client-int-config        # matches <app>-config in envFrom
    envs:
      - client-config-int.env

